name: mark_to_rtf
description: A lightweight macOS application for converting Markdown to RTF
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  markdown: ^7.1.1
  clipboard: ^0.1.3
  system_tray: ^2.0.3
  window_manager: ^0.3.7
  flutter_highlight: ^0.7.0
  hotkey_manager: ^0.1.7
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: SFMono
      fonts:
        - asset: assets/fonts/SFMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFMono-Medium.ttf
          weight: 500
